name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          show-progress: ''
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: |
            **/*.md
            #node_modules
  textlint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          show-progress: ''
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: textlint
        run: npm run textlint
  vale-lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          show-progress: ''
      - name: vale
        uses: vale-cli/vale-action@v2
        with:
          fail_on_error: false
